DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  `version` MEDIUMINT UNSIGNED NOT NULL DEFAULT '1',
  email VARCHAR(255) NOT NULL,
  passwd VARCHAR(255) DEFAULT NULL,
  time_zone VARCHAR(50) NOT NULL DEFAULT 'America/Los_Angeles',
  active TINYINT(1) DEFAULT 0,
  birth_date DATETIME NOT NULL,
  create_date DATETIME NOT NULL,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX users_email_udx (email)
) ENGINE=INNODB;